pragma Singleton

import Quickshell
import Quickshell.Io
import QtQuick
import qs.config

// Colour surfaces for the shell.
//
// Two sources, selected by Config.theme.name:
//
//   "dynamic"  -> ~/.cache/hellwal/quickshell.json, regenerated by hellwal
//                 whenever the wallpaper changes (waypaper post_command).
//                 Watched, so a wallpaper change recolours the shell live with
//                 no restart. This replaces the old waybar-watcher.sh inotify
//                 loop, which had to restart waybar to achieve the same thing.
//
//   "<name>"   -> theme/<name>.json in the shell directory, a fixed palette.
//
// Both files provide a `roles` object. Anything missing from it falls back to
// the constants below, so a partial or truncated theme file degrades to
// something readable rather than rendering black-on-black.
//
// `urgent` is deliberately NOT wallpaper-derived. hellwal produces a palette
// sampled from the image, and on a cool-toned wallpaper the nearest thing to
// an alert colour came out as pale blue (#66b6d8) - useless for signalling
// urgency. A static theme may override it; the dynamic source may not.
Singleton {
  id: root

  // ---- fallbacks -------------------------------------------------------
  readonly property color fallbackBackground: "#101315"
  readonly property color fallbackForeground: "#cacccc"
  readonly property color fallbackAccent: "#27959c"
  readonly property color fallbackAccentAlt: "#4bc4d2"
  readonly property color fallbackMuted: "#6b7a7a"
  readonly property color fallbackUrgent: "#d05c5c"

  readonly property string themeName: (Config.theme && Config.theme.name) || "dynamic"
  readonly property bool isDynamic: root.themeName === "dynamic"

  readonly property string dynamicPath: Quickshell.env("HOME") + "/.cache/hellwal/quickshell.json"
  readonly property string staticPath: Quickshell.shellPath("theme/" + root.themeName + ".json")

  // Parsed `roles` from whichever source is active.
  property var roles: ({})

  // ---- foundational palette -------------------------------------------
  function pick(key, fallback) {
    const v = root.roles[key];
    return (typeof v === "string" && v.length > 0) ? v : fallback;
  }

  // ---- contrast guards -------------------------------------------------
  // A wallpaper-derived palette carries no guarantee that its colours are
  // readable against its own background. A real example: the "skeleton in the
  // sky" wallpaper yields background #000003 and color9 #2a0a0a, giving a
  // muted-on-background contrast of 1.14:1 - the window title and empty
  // workspace numbers render as near-black on near-black and simply vanish.
  //
  // So rather than trusting the palette, any role used for text is nudged
  // toward the foreground until it clears a minimum contrast ratio. Colours
  // that are already readable pass through untouched, which means a
  // well-behaved static theme is never altered.

  // WCAG relative luminance.
  function luminance(c) {
    function ch(v) {
      return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    }
    return 0.2126 * ch(c.r) + 0.7152 * ch(c.g) + 0.0722 * ch(c.b);
  }

  function contrast(a, b) {
    const la = root.luminance(a);
    const lb = root.luminance(b);
    return (Math.max(la, lb) + 0.05) / (Math.min(la, lb) + 0.05);
  }

  function mix(a, b, t) {
    return Qt.rgba(a.r + (b.r - a.r) * t, a.g + (b.g - a.g) * t, a.b + (b.b - a.b) * t, 1);
  }

  // Blend `c` toward `towards` in small steps until it clears `target` against
  // `against`. Steps rather than solving directly so the result keeps as much
  // of the original hue as possible - we want a dimmed version of the theme
  // colour, not a slide all the way to plain foreground.
  function ensureContrast(c, against, target, towards) {
    if (root.contrast(c, against) >= target)
      return c;
    for (let t = 0.1; t < 1.0; t += 0.1) {
      const candidate = root.mix(c, towards, t);
      if (root.contrast(candidate, against) >= target)
        return candidate;
    }
    return towards;
  }

  readonly property color background: root.pick("background", root.fallbackBackground)
  readonly property color foreground: root.pick("foreground", root.fallbackForeground)

  // These MUST be declared as `property color`, not passed as raw pick()
  // results. pick() returns a string; QML only coerces it to a color when it
  // is assigned to a color-typed property. Handing the bare string to
  // ensureContrast() leaves c.r/c.g/c.b undefined, luminance() returns NaN,
  // every >= comparison is false, and the guard silently walks all the way to
  // `towards` - turning every colour into plain foreground.
  readonly property color rawAccent: root.pick("accent", root.fallbackAccent)
  readonly property color rawAccentAlt: root.pick("accentAlt", root.fallbackAccentAlt)
  readonly property color rawMuted: root.pick("muted", root.fallbackMuted)
  readonly property color rawUrgent: root.pick("urgent", root.fallbackUrgent)

  // 3:1 across the board - the WCAG floor for large text and non-text UI.
  //
  // Uniform rather than stricter-for-muted on purpose: Catppuccin Mocha's
  // overlay0 (#6c7086) sits at 3.36:1 against its base, which is a deliberate
  // design decision by people who thought about it. A 3.5 threshold "fixed"
  // it to #767a91, i.e. quietly overrode a hand-tuned theme. 3.0 leaves any
  // considered palette alone and still rescues the degenerate wallpaper cases.
  readonly property real minContrast: 3.0

  readonly property color accent: root.ensureContrast(root.rawAccent, root.background, root.minContrast, root.foreground)
  readonly property color accentAlt: root.ensureContrast(root.rawAccentAlt, root.background, root.minContrast, root.foreground)
  readonly property color muted: root.ensureContrast(root.rawMuted, root.background, root.minContrast, root.foreground)

  // Unified hover fill for any interactive element (bar buttons, popup
  // buttons, pills, rows). One alpha everywhere so every clickable thing
  // reads the same on hover.
  readonly property color hover: Qt.alpha(root.accentAlt, 0.15)

  // Static themes may override urgent; the hellwal template does not emit it.
  // Guarded too, so a theme cannot make an alert invisible.
  readonly property color urgent: root.ensureContrast(root.rawUrgent, root.background, root.minContrast, root.foreground)

  // ---- derived surfaces ------------------------------------------------
  // The stable contract widgets bind to. Unchanged from phase 2, which is why
  // swapping the colour source needed no widget edits.
  readonly property QtObject bar: QtObject {
    readonly property color background: Qt.alpha(root.background, Config.bar.transparent ? 0.0 : 0.85)
    readonly property color text: root.foreground
    readonly property color textMuted: root.muted
    readonly property color border: Qt.alpha(root.accent, 0.25)
  }

  readonly property QtObject workspace: QtObject {
    readonly property color active: root.accentAlt
    readonly property color occupied: root.accent
    readonly property color empty: root.muted
    readonly property color urgent: root.urgent
    readonly property color hover: root.hover
  }

  readonly property QtObject popup: QtObject {
    readonly property color background: Qt.alpha(root.background, 0.95)
    readonly property color text: root.foreground
    readonly property color border: Qt.alpha(root.accent, 0.4)
  }

  // ---- loading ---------------------------------------------------------
  function apply(text, label) {
    const t = String(text || "").trim();
    if (!t) {
      root.roles = ({});
      return;
    }
    try {
      const parsed = JSON.parse(t);
      root.roles = (parsed && typeof parsed.roles === "object" && parsed.roles) || ({});
    } catch (e) {
      console.warn(`theme: ${label} parse failed, using fallback palette: ${e}`);
      root.roles = ({});
    }
  }

  function reload() {
    if (root.isDynamic)
      root.apply(dynamicFile.text(), "hellwal quickshell.json");
    else
      root.apply(staticFile.text(), root.themeName + ".json");
  }

  onThemeNameChanged: root.reload()

  // Same construction-order problem as Config: the FileViews below have
  // already fired onLoaded by the time this singleton is complete, so read
  // once explicitly.
  Component.onCompleted: root.reload()

  FileView {
    id: dynamicFile
    path: root.dynamicPath
    blockLoading: true
    watchChanges: true
    printErrors: false
    onLoaded: if (root.isDynamic) root.reload()
    onFileChanged: reload()
    onLoadFailed: {
      if (root.isDynamic)
        console.warn("theme: no hellwal quickshell.json yet, using fallback palette");
    }
  }

  FileView {
    id: staticFile
    path: root.staticPath
    blockLoading: true
    watchChanges: true
    printErrors: false
    onLoaded: if (!root.isDynamic) root.reload()
    onFileChanged: reload()
    onLoadFailed: {
      if (!root.isDynamic)
        console.warn(`theme: could not read ${root.themeName}.json, using fallback palette`);
    }
  }
}
