hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon & awww img")
  hl.exec_cmd('waybar -s "/home/tibtab/.cache/hellwal/style.css"')
  hl.exec_cmd("nvidia-settings --load-config-only")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("hyprpm reload -n")
  hl.exec_cmd("fcitx5")
  hl.exec_cmd("gsr-ui launch-daemon")
end)
