return {
  {
    'xiyaowong/transparent.nvim',
    opts = {
      extra_groups = {
        'NeoTreeCursorLine',
        'NeoTreeDimText',
        'NeoTreeDirectoryIcon',
        'NeoTreeDirectoryName',
        'NeoTreeDotfile',
        'NeoTreeFileIcon',
        'NeoTreeFileName',
        'NeoTreeFileNameOpene',
        'NeoTreeFilterTerm',
        'NeoTreeFloatBorder',
        'NeoTreeFloatTitle',
        'NeoTreeTitleBar',
        'NeoTreeGitAdded',
        'NeoTreeGitConflict',
        'NeoTreeGitDeleted',
        'NeoTreeGitIgnored',
        'NeoTreeGitModified',
        'NeoTreeGitUnstaged',
        'NeoTreeGitUntracke',
        'NeoTreeGitStaged',
        'NeoTreeHiddenByName',
        'NeoTreeIndentMarker',
        'NeoTreeExpander',
        'NeoTreeNormal',
        'NeoTreeNormalNC',
        'NeoTreeSignColumn',
        'NeoTreeStatusLine',
        'NeoTreeStatusLineNC',
        'NeoTreeVertSplit',
        'NeoTreeWinSeparator',
        'NeoTreeEndOfBuffer',
        'NeoTreeRootName',
        'NeoTreeSymbolicLinkTarget',
        'NeoTreeTitleBar',
        'NeoTreeWindowsHidden',
      },
    },
  },
  {
    'catppuccin/nvim',
    lazy = true,
    priority = 1000,
    name = 'catppuccin',
    opts = {
      flavour = 'mocha',
    },
    init = function()
      vim.cmd.colorscheme 'catppuccin'
      vim.api.nvim_set_hl(0, 'LineNr', { fg = '#cdd6f4' })
    end,
  },
}
