[general]
import = ["/home/tibtab/.cache/wal/colors-alacritty.toml"]
live_config_reload = true

[terminal.shell]
program = "/usr/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9

[font]
normal.family = "SpaceMono Nerd Font Mono"
bold.family = "SpaceMono Nerd Font Mono"
italic.family = "SpaceMono Nerd Font Mono"
bold_italic.family = "SpaceMono Nerd Font Mono"

size = 24.0

